# Generated by Django 3.1.5 on 2021-01-09 14:40

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.DecimalField(decimal_places=10, max_digits=20)),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField()),
                ('sensorType', models.CharField(max_length=50)),
            ],
        ),
    ]
